src/Entity/Mood.php
<?php

namespace App\Entity;

use App\Repository\MoodRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MoodRepository::class)
 */
class Mood
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $feeling;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $emoji;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=UserProfile::class, inversedBy="moods")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $likesCount;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFeeling(): ?string
    {
        return $this->feeling;
    }

    public function setFeeling(string $feeling): self
    {
        $this->feeling = $feeling;

        return $this;
    }

    public function getEmoji(): ?string
    {
        return $this->emoji;
    }

    public function setEmoji(string $emoji): self
    {
        $this->emoji = $emoji;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUserId(): ?UserProfile
    {
        return $this->user_id;
    }

    public function setUserId(?UserProfile $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getLikesCount(): ?int
    {
        return $this->likesCount;
    }

    public function setLikesCount(?int $likesCount): self
    {
        $this->likesCount = $likesCount;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">
                        Friendface
                    </a>
                </div>
            </div>
        </nav>
        {# the content of the page #}
        <main class="container">
            {% block body %}{% endblock %}
        </main>
        <script 
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" 
            integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" 
            crossorigin="anonymous" 
            referrerpolicy="no-referrer"></script>
        <script 
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" 
            integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" 
            crossorigin="anonymous"></script>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/moods.html.twig
{% extends "base.html.twig" %}

{% block title %}Moods{% endblock %}

{% block body %}
    <div>
        <h1>All Moods</h1>
        <h6>There are currently {{ moods|length }} moods logged...
    </div>
    <div class="row">
        {% for mood in moods %} {#for loop looks in twig #}
            <div class="col-12" style="background-color:#f9f9f8; padding: 20px; margin-top: 20px;">
                <h6 style="float:right">{{ mood.userId.username }}</h6>
                <h5>{{ mood.emoji }} - {{ mood.feeling }}</h5>
                <p> {{ mood.description }}</p>
                {# like button #}
                <div class="likeButton btn btn-warning" style="float:left" data-id="{{ mood.id }}">
                    Like &nbsp;
                    <p style="float:right">{{ mood.likesCount }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="../js/likes.js"></script>
{% endblock %}

templates/profile.html.twig
{% extends "base.html.twig" %}

{% block title %}Profile Page{% endblock %}

{% block body %}
    <div class="row">
        This is the profile of {{ user.username }} ({{ user.email }}) and they have {{ user.friends|length }} friends:
    </div>
    <div class="row">
        <ul>
            {% for friend in user.friends %} {#for loop looks in twig #}
                <li>{{ friend.username }}</li>
            {% endfor %}
        </ul>
    </div>
    <div>
        <h6>My Moods</h6>
    </div>
    <div class="row">
        {% for mood in user.moods %} {#for loop looks in twig #} {#moods from our Mood Entity#}
            <div class="col-12" style="background-color:#f9f9f8; padding: 20px; margin-top: 20px;">
                <h5>{{ mood.emoji }} - {{ mood.feeling }}</h5>
                <p> {{ mood.description }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/register.html.twig
{% extends "base.html.twig" %}

{% block title %}Register{% endblock %}

{% block body %}
    <div>

        {% if error %}
            <div>Oops!</div>
        {% endif %}
        {{title}}
        {{ form_start(form, {'attr': {'no-validate': 'no-validate'}}) }} {# opening the form#}

           {{form_widget(form.username, { 'attr': {'class': 'form-control', 'placeholder': 'Username', 'style': 'margin: 10px'} }) }}
           {{form_widget(form.email, { 'attr': {'class': 'form-control', 'placeholder': 'Email', 'style': 'margin: 10px'} }) }}
           {{form_widget(form.password, { 'attr': {'class': 'form-control', 'placeholder': 'Password', 'style': 'margin: 10px'} }) }}

           {{form_widget(form.submit, { 'attr': {'class': 'btn'} }) }}

        {{ form_end(form) }} {# closing the form #}
    </div>
{% endblock %}